# version: '3.8'

# services:

#   app:
#     build: .
#     container_name: API_data
#     restart: always
#     ports:
#       - "8000:8000"
#     # env_file:
#     #   - .env
#     volumes:
#       - .:/API_data
#     command: ["uvicorn", "API_data:app", "--host", "0.0.0.0", "--port", "8000"]


version: '3.8'

services:
  app:
    build: .
    container_name: API_data
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/API_data
    depends_on:
      - redis
    command: ["uvicorn", "API_data:app", "--host", "0.0.0.0", "--port", "8000"]

  celery_worker:
    build: .
    container_name: celery_worker
    command: ["celery", "-A", "invoice_tasks", "worker", "--loglevel=info"]
    depends_on:
      - redis
      - app

  redis:
    image: redis:alpine
    container_name: redis
